baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Tillmann Seiffert'

[menus]

  [[menus.main]]
    name = 'Editing'
    pageRef = '/editing'
    weight = 30

  [[menus.main]]
    name = 'about'
    pageRef = '/about'
    weight = 20

  [[menus.main]]
    name = 'OnSet'
    pageRef = '/onset'
    weight = 30

  [[menus.main]]
    name = 'contact'
    pageRef = '/contact'
    weight = 10

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
