baseURL = 'https://tillmannseiffert.de'
languageCode = 'en-US'
title = 'Tillmann Seiffert'

[menus]

  [[menus.main]]
    name = 'Editing'
    pageRef = '/editing'
    weight = 10

  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 30

  [[menus.main]]
    name = 'On Set'
    pageRef = '/onset'
    weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
